### ISSUE TITLE
Tag 

### ISSUE THREAD

**Issue by yuuues** [Dofamin/MTProxy-Docker#6]
Checking older commits ebd4acb8a1ca60f176d0b62f72920ded7f256c07 i saw that the TAG was removed so i cannot send to the image the values from the MTProxybot.

what i should do to allow that parameter?

Adding to the container-image-root/entrypoint.sh the -P $TAG would be enough?

Thanks :)

**Comment by Dofamin** [comment]
Hello, @Kytoh 
The tag was removed because it was not used anywhere
it will not have an effect in entry point, since entry point will only try to complete the part that you tell it to do. 
https://github.com/Dofamin/MTProxy-Docker/blob/main/container-image-root/entrypoint.sh#L9-L14

So that I can better understand the essence of your problem, please describe the use in your case.

**Comment by yuuues** [comment]
Checking the docs from both mtproto_repos

> Register your proxy with [@MTProxybot](https://t.me/MTProxybot) on Telegram.
> Set received tag with arguments: -P proxy tag

If i cannot configure the TAG parameter, how i should fill that proxy tag?

**Comment by Dofamin** [comment]
you can:
1. make a docker run indicating the entire command and additional parameters that you need or don't need
`./mtproto-proxy -u nobody -p 8888 -H 8889 -S $SECRET --aes-pwd proxy-secret proxy-multi.conf -M $WORKERS --nat-info $(hostname --ip-address):$IP --http-stats  <ur tags>`

generic example:  `docker run -it  ubuntu:22.04 /bin/bash`

2. rework the code so that you can use the tag key inside the project right away

I note that the -P key is only needed for registered proxies, the proxy itself will work without registration
